USER_NOT_FOUND="User Details Not Found"
ORGANISATION_NOT_FOUND="Organisation Not Found"
ROLE_NOT_FOUND="Role Not Found"
DASHBOARD_NOT_FOUND="Dashboard Not Found"
GROUP_NOT_FOUND="Group Not Found"
TENANT_NOT_FOUND="Tenant Not Found"
COMPANY_PROFILE="Company Profile Not Found"
PAGE_NOT_FOUND="Pages Details Not Found"
DETAILS_NOT_FOUND="Deatils Not Found"
KPI_NOT_FOUND="Kpis Not Found"

